baseURL = 'https://blog.tot.yt/'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
defaultContentLanguage = 'zh-cn'
theme = 'farallon'


[langusges]
[languages.en]
  title = "ToT Blog"
  languageName = "English"
  contentDir = 'content/en'
  [languages.en.menu]
    [[languages.en.menu.main]]
    name="Gears"
    url="/en/gears/"
    weight="2"
    [[languages.en.menu.main]]
    name="Movies"
    url="/en/movies/"
    weight="1"
    [[languages.en.menu.main]]
    name="Categories"
    url="/en/categories/"
    weight="1"
    [[languages.en.menu.main]]
    name="Tags"
    url="/en/tags/"
    weight="1"
    [[languages.en.menu.main]]
    name="About"
    url="/en/about/"
    weight="5"
    [[languages.en.menu.main]]
    name="Stories"
    url="/en/archives/"
    weight="1"

[languages.zh-cn]
  title = "ToT Blog"
  languageName = "简体中文"
  contentDir = 'content/zh-cn'
  [languages.zh-cn.menu]
    [[languages.zh-cn.menu.main]]
    name="好物"
    url="/gears/"
    weight="2"
    [[languages.zh-cn.menu.main]]
    name="豆瓣"
    url="/movies/"
    weight="3"
    [[languages.zh-cn.menu.main]]
    name="分类"
    url="/categories/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="标签"
    url="/tags/"
    weight="1"
    [[languages.zh-cn.menu.main]]
    name="文章"
    url="/archives/"
    weight="1"

[taxonomies]
  category = 'categories'
  tag = 'tags'

[Params]
  search= true
  description = 'A simple and fast blog framework written in Go.'
  toc = true
  mainSections = ['archives','memo']
  indexName = 'bigfa'
  searchKey = 'cde4710ac37be59cc3284179deb3a37b'
  searchAPPID = 'LG3447W3ML'
  showAuthor = false
  authorName = '浪子'
  authorDescription = '曾梦想仗剑走天涯'
  authorAvatar = 'https://img.imsun.org/avatar.jpg'
  commentDomain = 'https://t.loliko.cn'
  telegram = 'https://t.me/'
  feed = '/index.xml'
  twitter = '/'
  instagram = '/'
  github = 'https://github.com/jkjoy'
  footer_sns = true

[outputs]
  home = [ "HTML","JSON","RSS","SITEMAP"]
  page = ["HTML"]


[markup.tableOfContents]
    endLevel = 5
    startLevel = 3
